model_name: "google/siglip2-base-patch16-224"
seed: 109

data:
  dataset: "ssv2"
  base_dir: "/root/data/20bn-something-something-v2"                  # Location containing *.webm files
  annotation_dir: "/root/data/labels"     # Location containing labels.json, train.json, validation.json
  test_splits_dir: "/root/action-siglip/datasets_splits/ssv2_splits" 
  test_file: "test_with_labels.txt"
  split: 1                                # Ignored for SSv2
  num_segments: 8
  workers: 8

modes:
  baseline_with_lora:
    checkpoint_dir: "./exp/siglip2_peft/ssv2/baseline_with_lora"
    log_file: "./exp/siglip2_peft/ssv2/baseline_with_lora/session.log"
    
    unfreeze_backbone: false
    prompt_type: "manual"
    manual_prompt_template: "A video of a person performing {}"
    cocoop_hidden_dim: 512
    
    lora_r: 16                   
    lora_alpha: 16.0            
    lora_dropout: 0.05          
    lora_target_modules: ["q_proj", "v_proj"]

    batch_size: 16              
    accumulation_steps: 2       # 16 * 2 = 32 effective batch size
    
    lr_base: 3.0e-4             
    lr_head: 2.0e-3             
    weight_decay: 0.05          
    
    num_epochs: 30              
    warmup_epochs: 5            # Sử dụng Linear Warmup trong 5 epochs đầu
    early_stopping_patience: 5