model_name: "google/siglip2-base-patch16-224"
seed: 1024

data:
  dataset: "ssv2"
  base_dir: "/root/data/20bn-something-something-v2"                  # Location containing *.webm files
  annotation_dir: "/root/data/labels"     # Location containing labels.json, train.json, validation.json
  split: 1                                # Ignored for SSv2
  num_segments: 8
  workers: 8

modes:
  base:
    batch_size: 16
    num_epochs: 20
    lr_base: 0.0001
    lr_head: 0.001
    weight_decay: 0.01
    checkpoint_dir: "checkpoints/ssv2"
    prompt_type: "manual"
    manual_prompt_template: "{}"
    cocoop_hidden_dim: 512
    lora_r: 16
    lora_alpha: 16
    lora_dropout: 0.1
    lora_target_modules: ["q_proj", "v_proj"]
    unfreeze_backbone: false
    early_stopping_patience: 5

  zero_shot:
    batch_size: 16
    num_epochs: 20
    lr_base: 0.0001
    lr_head: 0.001
    weight_decay: 0.01
    checkpoint_dir: "checkpoints/ssv2"
    prompt_type: "manual"
    manual_prompt_template: "{}"
    cocoop_hidden_dim: 512
    lora_r: 16
    lora_alpha: 16
    lora_dropout: 0.1
    lora_target_modules: ["q_proj", "v_proj"]
    unfreeze_backbone: false
    early_stopping_patience: 5